create table if not exists public."PREPARATION_LOG" (
  "PrepLogID" integer generated by default as identity primary key,
  "BookingID" integer null references public."BOOKING"("BookingID"),
  "MealPrepOrderID" integer null references public."MEAL_PREP_ORDER"("MealPrepOrderID"),
  "CycleDate" date null,
  "PreparedAt" timestamptz not null default now(),
  constraint preparation_log_exactly_one_order check (("BookingID" is not null)::integer + ("MealPrepOrderID" is not null)::integer = 1)
);

create unique index if not exists preparation_log_booking_unique on public."PREPARATION_LOG" ("BookingID") where "BookingID" is not null;
create unique index if not exists preparation_log_cycle_unique on public."PREPARATION_LOG" ("MealPrepOrderID", "CycleDate") where "MealPrepOrderID" is not null;

create table if not exists public."STOCK_ADJUSTMENT" (
  "AdjustmentID" integer generated by default as identity primary key,
  "PrepLogID" integer not null references public."PREPARATION_LOG"("PrepLogID"),
  "IngredientID" integer not null references public."INGREDIENT"("IngredientID"),
  "Delta" numeric not null,
  "Reason" text not null,
  "CreatedAt" timestamptz not null default now()
);

alter table public."PREPARATION_LOG" enable row level security;
alter table public."STOCK_ADJUSTMENT" enable row level security;
revoke all on public."PREPARATION_LOG", public."STOCK_ADJUSTMENT" from anon, authenticated;

create or replace function public.mark_prepared(
  p_operator_id integer,
  p_booking_id integer default null,
  p_meal_prep_order_id integer default null,
  p_cycle_date date default null,
  p_usage jsonb default '[]'::jsonb
) returns integer
language plpgsql security definer set search_path = ''
as $$
declare
  v_log_id integer;
  v_usage jsonb;
  v_ingredient public."INGREDIENT"%rowtype;
  v_ingredient_id integer;
  v_quantity numeric;
begin
  insert into public."PREPARATION_LOG" ("BookingID", "MealPrepOrderID", "CycleDate")
  values (p_booking_id, p_meal_prep_order_id, p_cycle_date)
  returning "PrepLogID" into v_log_id;

  for v_usage in select value from jsonb_array_elements(p_usage)
  loop
    v_ingredient_id := (v_usage->>'ingredientId')::integer;
    v_quantity := (v_usage->>'quantity')::numeric;
    if v_quantity is null or v_quantity <= 0 then raise exception 'Invalid ingredient quantity'; end if;
    select * into v_ingredient from public."INGREDIENT" where "IngredientID" = v_ingredient_id for update;
    if not found or v_ingredient."OperatorID" <> p_operator_id then raise exception 'Ingredient % is not owned by this operator', v_ingredient_id; end if;
    if v_ingredient."CurrentStock" < v_quantity then raise exception 'Insufficient stock for %', v_ingredient."IngredientName"; end if;
    update public."INGREDIENT" set "CurrentStock" = "CurrentStock" - v_quantity where "IngredientID" = v_ingredient_id;
    insert into public."STOCK_ADJUSTMENT" ("PrepLogID", "IngredientID", "Delta", "Reason") values (v_log_id, v_ingredient_id, -v_quantity, 'Order prepared');
  end loop;
  return v_log_id;
exception when unique_violation then
  raise exception 'This order or meal-prep cycle is already prepared';
end;
$$;
revoke execute on function public.mark_prepared(integer, integer, integer, date, jsonb) from anon, authenticated;
grant execute on function public.mark_prepared(integer, integer, integer, date, jsonb) to service_role;
